### ISSUE TITLE
Investigate dedicated "calloop" support

### ISSUE THREAD

**Issue by fogti** [jazzfool/reclutch#15]
splitted off #13. The question is: Should we add dedicated calloop support to `reclutch_event`?

`winit` uses `calloop` internally, but doesn't expose the full API. `calloop` itself is way more low-level. It's an event loop implementation, as such, it fits into the realm of `reclutch_event`. If we add support, it's unclear how much/what to include, because `calloop` wraps serval things.

Related:
* [`calloop` docs](https://docs.rs/calloop/0.4.4/calloop/index.html)
* rust-windowing/winit#1292

**Comment by jazzfool** [comment]
It seems that `winit` uses `calloop` only for Linux targets.
Also, the most suitable "host" for `reclutch` is `winit`, which already has event loop event integration with `winit`.

I'm also not sure how well it would integrate with the current event API without making drastic changes.
