### ISSUE TITLE
What's the purpose of VerbGraphContext?

### ISSUE THREAD

**Issue by fogti** [jazzfool/reclutch#20]
I looked through the `reclutch_verbgraph` source code and found an practically-unit struct `VerbGraphContext`, which currently doesn't seem to have a real usage which would benefit from it. To test my assumption, I created a branch ([`no-ctx-needed`](https://github.com/zserik/reclutch/tree/no-ctx-needed)) which got rid of it and replaced it with a freestanding function which provides a similiar interface.

@jazzfool What's the purpose and intent of `VerbGraphContext`?

**Comment by zserik** [comment]
tag: `documentation`

**Comment by jazzfool** [comment]
I'm still not certain on the design of `verbgraph`. Also, it could allow for back-tracing the graph for debugging purposes.

**Comment by jazzfool** [comment]
Actually, it could be used to detect infinite loops (as in two procedures bouncing between each other), but I'm not sure how to implement that for anything other that trivial dependencies, since it could be tricked by making a bogus dependency right before the actual circular dependency.

**Comment by jazzfool** [comment]
Fixed in a70d187f2b1592611ee20b301de7a10d2210e583
