### ISSUE TITLE
`opengl` example fails to render Skia on macOS

### ISSUE THREAD

**Issue by ctrlcctrlv** [jazzfool/reclutch#26]
![image](https://user-images.githubusercontent.com/838783/92269308-c7a2db00-ee98-11ea-82e0-c7cee81ea5eb.png)
![image](https://user-images.githubusercontent.com/838783/92269383-edc87b00-ee98-11ea-8e8e-925ccb926ae2.png)

Cf. mfeq/Qglif#2

**Comment by ctrlcctrlv** [comment]
Just so you know, the `shaping` example has problems too. It flashes between correct display and garbage from VRAM as I move the mouse around.
The `counter` and `image_viewer` examples fail to resize correctly.

**Comment by jazzfool** [comment]
This appears to be a bug with shared OpenGL textures on MacOS. A disclaimer has been added in the README.
