### ISSUE TITLE
Why not publish it on crates.io?

### ISSUE THREAD

**Issue by sumibi-yakitori** [jazzfool/reclutch#27]
I stumbled upon this interesting library today.

Why not publish it on crates.io?
Generally speaking, not publishing it on crates.io makes it difficult for people to find this library.

**Comment by jazzfool** [comment]
I don't think there are enough people using this library to make it worthwhile. There also isn't any specific release version so it's no different to pulling directly from the repo in the Cargo.toml.

**Comment by sumibi-yakitori** [comment]
Okay.
I do think that publicizing it would give people access to the doc.rs reference, and that might encourage more people to try it out and use it more.
