### ISSUE TITLE
Tracking issue: Error reporting

### ISSUE THREAD

**Issue by fogti** [jazzfool/reclutch#6]
It might be a good idea to revisit the choice of using `failure` for error reporting in the `display` backend. Maybe a smaller and/or more modern error handling crate should/could be used.

**Comment by jazzfool** [comment]
I agree, error handling in general is quite lazy. What do you propose instead? I was thinking perhaps [snafu](https://crates.io/crates/snafu)?

**Comment by fogti** [comment]
[`anyhow`](https://crates.io/crates/anyhow) and [`thiserror`](https://crates.io/crates/thiserror) should also be considered.

**Comment by fogti** [comment]
I think `snafu` might be a too big dependency.

**Comment by jazzfool** [comment]
`thiserror` seems to be the best fit for library code. I'll begin porting the `display` module soon.
